/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/tools/tree/master/packages/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   calendar-lite.js
 */


// tslint:disable:variable-name Describing an API that's defined elsewhere.
// tslint:disable:no-any describes the API as best we are able today

import {PolymerElement, html} from '@polymer/polymer/polymer-element.js';

import {GestureEventListeners} from '@polymer/polymer/lib/mixins/gesture-event-listeners.js';

declare class CalendarLite {
  date: Date|null|undefined;
  currentMonth: number|null|undefined;
  currentDay: number|null|undefined;
  minDate: Date|null|undefined;
  maxDate: Date|null|undefined;
  disabledDays: any[]|null|undefined;
  currentYear: number|null|undefined;
  mainColor: string|null|undefined;
  multiSelect: object|null|undefined;
  days: any[]|null|undefined;
  separator: any[]|null|undefined;
  disabledWeekDay: any[]|null|undefined;
  prettyDate: string|null|undefined;
  format: string|null|undefined;

  /**
   * to get number of days in a month
   */
  monthDays(date: any): any;
  ready(): void;
  _getUpdated(d: any, type: any): any;
  generateTable(): void;
  _getDayClass(s: any, d: any): any;
  _setDate(e: any): void;
  prettyDateChanged(newPrettyDate: any): void;
  _keyPressSelect(e: any): void;
  triggerEvent(e: any, data: any): void;
  _setYear(e: any): void;
  _setMonth(e: any): void;
  _show(e: any): void;
  pagination(): void;
  _generateYears(min: any, max: any, tmpArray: any): void;
  _populate(newDate: any, oldDate: any): void;
  dateFormat(date: any): any;
  monthFormat(): any;
  yearFormat(): any;
  _swipeNextMonth(): void;
  changeView(x: any): void;
  _once(eventName: any, callback: any, node: any): void;
  _swipePrevMonth(): void;
  _getDays(row: any): any;
  _whichAnimationEnd(): any;
}

declare global {

  interface HTMLElementTagNameMap {
    "calendar-lite": CalendarLite;
  }
}
