/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/tools/tree/master/packages/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   time-input.js
 */


// tslint:disable:variable-name Describing an API that's defined elsewhere.
// tslint:disable:no-any describes the API as best we are able today

import {PolymerElement, html} from '@polymer/polymer/polymer-element.js';

declare class TimeInput extends PolymerElement {
  value: string|null|undefined;
  readonly: boolean|null|undefined;
  required: boolean|null|undefined;
  disabled: boolean|null|undefined;
  autoValidate: boolean|null|undefined;
  hoursInput: number|null|undefined;
  minutesInput: number|null|undefined;
  label: string|null|undefined;
  invalid: boolean|null|undefined;
  hideIcon: boolean|null|undefined;
  errorMessage: string|null|undefined;
  _valueChanged(newValue: any): void;
  computeTime(hours: any, minutes: any): void;
  _formatHour(): void;
  _formatMinutes(): void;
  _isValidHours(): any;
  _isValidMinutes(): any;
  _clearData(): void;
  validate(): any;
}

declare global {

  interface HTMLElementTagNameMap {
    "time-input": TimeInput;
  }
}
